problemHeader = "The Problem"
problem = "A sheet of cardboard is rectangular, 25 cm long and 15 cm wide.\nCongruent squares are to be cut from their four corners.\nThe resulting piece of cardboard is to be folded and its edges taped to\nform an open-topped box.\nHow should this be done to get a box of the largest possible volume?"
b1t = "25cm x 15cm cardboard sheet"
b2t = "Congruent squares with side length x"
b3t = "Crease lines equal to SIDE - 2x"
at = "Box after folding"